[package]
name = "notecrypt-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
test-support = []

[dependencies]
blake3.workspace = true
crossbeam-channel.workspace = true
constant_time_eq.workspace = true
getrandom.workspace = true
notecrypt-core.workspace = true
notecrypt-crypto.workspace = true
notecrypt-platform-fs.workspace = true
notecrypt-replication.workspace = true
notecrypt-store.workspace = true
zeroize.workspace = true

[dev-dependencies]
notecrypt-platform-fs = { workspace = true, features = ["test-support"] }
notecrypt-store = { workspace = true, features = ["test-support"] }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
trybuild.workspace = true

[lints]
workspace = true
